# environment.yml
#
# Created on Tue Nov 14 2023 by Florian Pfleiderer
#
# Copyright (c) 2023 TU Wien

name: cyws3d
channels:
  - pytorch
  - iopath
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.10.1 
  - torchvision=0.11.2 
  - cudatoolkit=11.3.1
  - fvcore 
  - iopath
  - pytorch3d=0.7.1
  - shapely
  - pip=23.1
  - pip:
    - timm==0.6.12 
    - jsonargparse 
    - matplotlib 
    - imageio 
    - loguru 
    - einops 
    - wandb 
    - easydict 
    - kornia==0.6.8 
    - scipy 
    - etils 
    - mmdet==2.25.3
    - segmentation-models-pytorch@git+https://github.com/ragavsachdeva/segmentation_models.pytorch.git@2cde92e776b0a074d5e2f4f6a50c68754f948015
    #- mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10/index.html